# General settings
seed: 42
device: cuda

# Dataset settings
dataset:
  name: CIFAR10
  train_batch_size: 128
  test_batch_size: 256
  num_workers: 4

# Model settings
model:
  name: ResNet18
  pretrained: false
  num_classes: 10

# Training settings
train:
  epochs: 50
  lr: 0.1
  momentum: 0.9
  weight_decay: 1e-4
  save_checkpoint: true
  checkpoint_path: ./checkpoints

# Testing settings
test:
  model_path: ./checkpoints/best.pth